### ISSUE TITLE
Failed to load a language-shellscript package grammar

### ISSUE THREAD

**Issue by NInjawolf19** [atom/language-shellscript#142]
Hi, I am new to Atom and this message and I have no idea to solve it because I look at almost every single discussion and nothing helps please help me and I want the way atom was before the message appeared please and you may need to explain the steps to me

please help [Photo](https://user-images.githubusercontent.com/50123501/56993231-c816bd80-6b50-11e9-85cd-426dbd536fbd.png)

**Comment by NInjawolf19** [comment]
it says

> [Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 ia32
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-shellscript](https://github.com/atom/language-shellscript) package 0.27.10


### Stack Trace

Failed to load a language-shellscript package grammar

```
At Cannot find module 'tree-sitter-bash.cson' in C:\Users\maste\.atom\packages\language-shellscript\grammars\tree-sitter-bash.cson

Error: Cannot find module 'tree-sitter-bash.cson'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.36.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:154765)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:3097676)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:360510)
    at l.readFile (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:360351)
    at ~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:11:581440
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
  at /packages/language-shellscript/grammars/tree-sitter-bash.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-console 0.4.6 
atom-terminal 0.8.0 
language-diff 0.7.0 
scroll-through-time 0.3.1 
```




>

**Comment by rsese** [comment]
It looks like you have language-shellscript installed manually?  language-shellscript is a core package so doesn't need to be installed - can you try uninstalling and see if that clears things up?

```
apm uninstall language-shellscript
```

**Comment by NInjawolf19** [comment]
@rsese How do you get to Apm uninstall language-shellscript do I type it into cmd, atom, PowerShell, I have no idea how to get to amp uninstall language-shellscript please tell me how.

**Comment by NInjawolf19** [comment]
sorry

**Comment by NInjawolf19** [comment]
I accidentally closed it

**Comment by NInjawolf19** [comment]
@rsese are you still there

**Comment by NInjawolf19** [comment]
Thanks

**Comment by rsese** [comment]
> @rsese How do you get to Apm uninstall language-shellscript do I type it into cmd, atom, PowerShell, I have no idea how to get to amp uninstall language-shellscript please tell me how.

Yes, you can copy/paste or type that exact command in cmd or PowerShell.

Do you remember if you specifically tried to install language-shellscript?

**Comment by jpavello** [comment]
Ihad the same issue from a fresh installation on Fedora. I actually fixed this error by **installing** the package

` apm install language-shellscript `

Despite the following  warning, it seems to work and I no longer get that error on startup
> The language-shellscript package is bundled with Atom and should not be explicitly installed.
You can run `apm uninstall language-shellscript` to uninstall it and then the version bundled
with Atom will be used.

**Comment by alexisfrjp** [comment]
Same problem here:
```
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/atom/resources/app.asar.unpacked/node_modules/tree-sitter-bash/build/Release/tree_sitter_bash_binding.node)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146819)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tree-sitter-bash/index.js:2:20)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tree-sitter-bash/index.js:15:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:695413)
    at new TreeSitterGrammar (/usr/share/atom/resources/app/static/<embedded>:11:3112550)
    at GrammarRegistry.createGrammar (/usr/share/atom/resources/app/static/<embedded>:11:360441)
    at /usr/share/atom/resources/app/static/<embedded>:11:360282
    at u (/usr/share/atom/resources/app/static/<embedded>:11:580950)
    at /usr/share/atom/resources/app/static/<embedded>:11:582203
    at electron/js2c/asar.js:571:9
    at FSReqCallback.wrapper [as oncomplete] (fs.js:483:5)
  at /usr/share/atom/resources/app.asar/node_modules/language-shellscript/grammars/tree-sitter-bash.json:1:1
```

* `apm install language-shellscript` doesn't solve anything, this popup comes back at the start-up of Atom.
* `language-shellscript` is a **Core Package**.

It was the same problem with `language-ruby`, I disabled both.

* **CentOS Linux release 7.8.2003**

**Comment by ptous** [comment]
Also same issue here, and matching alexisfrjp's report

```
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/atom/resources/app.asar.unpacked/node_modules/tree-sitter-bash/build/Release/tree_sitter_bash_binding.node)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tree-sitter-bash/index.js:2:20)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tree-sitter-bash/index.js:15:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:695413)
    at new TreeSitterGrammar (/usr/share/atom/resources/app/static/<embedded>:11:3112590)
    at GrammarRegistry.createGrammar (/usr/share/atom/resources/app/static/<embedded>:11:360436)
    at /usr/share/atom/resources/app/static/<embedded>:11:360277
    at u (/usr/share/atom/resources/app/static/<embedded>:11:580990)
    at /usr/share/atom/resources/app/static/<embedded>:11:582243
    at electron/js2c/asar.js:571:9
    at FSReqCallback.wrapper [as oncomplete] (fs.js:483:5)
  at /usr/share/atom/resources/app.asar/node_modules/language-shellscript/grammars/tree-sitter-bash.json:1:1
```
`CentOS Linux release 7.8.2003 (Core)`

No manual install of the grammar involved here - this cropped up after an upgrade to Atom `1.49.0`. Previously I was using `1.45.0`.

**Comment by pinacoelho** [comment]
> Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/atom/resources/app.asar.unpacked/node_modules/tree-sitter-bash/build/Release/tree_sitter_bash_binding.node)

> No manual install of the grammar involved here - this cropped up after an upgrade to Atom `1.49.0`. Previously I was using `1.45.0`.

Same here with RHEL 7.7 and 7.8

**Comment by zypA13510** [comment]
@alexisfrjp @ptous @pinacoelho I have the same issue as you, but sorry if I'm wrong, how is this related to the original issue (except the error message, i.e. title of this issue)? The OP hardly mentioned anything about glibc, and the stack trace, if you look at it, is different. As such I have created a new issue for this at #161. Please feel free to follow it.

**Comment by alexisfrjp** [comment]
Still in `1.51.0`. I give up Atom, I move to vscode.

**Comment by 32footsteps** [comment]
Fresh install of Atom on CentOS 7 threw this error along with `failed to load a language-ruby package grammar` for me.  I followed the script given in [https://github.com/atom/language-ruby/issues/279](#279) and installed gcc-5.4.  That also fixed this error (for me at least).

**Comment by ladar** [comment]
I got tired of waiting for the developers to fix this bug. And having to figure out the solution everytime I install atom on a RHEL/CentOS 7 system. So I finally wrote an install script that does it all for me. It's based on what others have posted, but this version will also install atom, and then go onto build gcc 5.4.0 and install it into the `/opt/gcc-5.4.0/` directory. Having it in `/usr/local/` means it could end up in your default search paths, and cause breakage. The script also modifies the `/usr/bin/atom` launcher, so it becomes the only app to make use of the freshly built libraries. 

```bash
#/bin/bash -x

echo "Downloading the atom rpm file..."
curl --location --output atom.x86_64.rpm https://atom.io/download/rpm

echo "Installing the atom rpm file..."
sudo yum -y install atom.x86_64.rpm

echo "Downloading gcc source files..."
curl --location --output gcc-5.4.0.tar.bz2 https://ftp.gnu.org/gnu/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2

echo "Extracting files..."
tar xvfj gcc-5.4.0.tar.bz2

echo "Installing dependencies..."
sudo yum -y install gmp-devel mpfr-devel libmpc-devel gcc-c++

echo "Configure and install..."
cd gcc-5.4.0 && ./configure --enable-languages=c,c++ --disable-multilib --prefix=/opt/gcc-5.4.0 && make -j$(nproc) && sudo make install

echo "Adding the library path to the atom launcher..."
sudo sed -i "11i\ \\nexport LD_LIBRARY_PATH=/opt/gcc-5.4.0/lib64/:\$LD_LIBRARY_PATH\\n" /usr/bin/atom

echo "Cleaning up the build directory..."
cd ../ && rm -rf atom.x86_64.rpm gcc-5.4.0.tar.bz2 gcc-5.4.0

echo "Install complete."
```
